---
# Add users here. Usernames must be unique
- username: exampleUser
  # Attributes may be flags with boolean values or have a string as value.
  # The keys may consist of valid printable ASCII characters except 'SPACE', '"', '\' and ':'
  # Scopes of the form "k:v" will be granted for a user
  # iff an attribute is registered here with key k and string-value v,
  # scopes without a ':' are granted iff an attribute with that key exists
  attributes:
  - key: omejdn
    value: admin
  - key: openid
    value: true
  - key: profile
    value: true
  - key: email
    value: admin@example.com
  # A password salted with BCrypt
  password: "$2a$12$Be9.8qVsGOVpUFO4ebiMBel/TNetkPhnUkJ8KENHjHLiDG.IXi0Zi"
